import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Form Validation Demo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="justify-center flex gap-4 bg-blue-500 text-white">
          <div className="">

          </div>
          <Link href="/">Native Validation</Link>
        </nav>
        <main className="container mx-auto max-w-4xl">
          {children}
        </main>
      </body>
    </html>
  );
}
